sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  global:
    - IMAGE="grantmacken/alpine-exist"
before_script:
  - docker pull "$IMAGE" || true
script:
  - docker build --pull --cache-from "$IMAGE" --tag "$IMAGE" .
  - docker run --name ex --publish 8080:8080 -d $IMAGE
  - docker ps
  - docker exec ex ls .
  - docker exec ex java -jar start.jar client -q -x 'system:get-version()'
  - curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/

after_script:
- docker images
